import {
  AudioLines,
  CircleStar,
  Cog,
  Dices,
  Droplets,
  Eye, EyeOff,
  Flame,
  Footprints,
  HeartCrack,
  Hourglass,
  Leaf,
  LensConcave,
  type LucideIcon,
  Moon,
  Shield,
  Skull,
  Snowflake,
  Sparkles,
  Stone,
  Sun,
  Sword,
  Swords,
  Target,
  TreePine,
  Wind,
  Zap,
} from 'lucide-react';

export interface StatusIconEntry { name: string; Icon: LucideIcon; }

export const STATUS_ICONS: StatusIconEntry[] = [
  { name: 'Flame', Icon: Flame },
  { name: 'Snowflake', Icon: Snowflake },
  { name: 'Skull', Icon: Skull },
  { name: 'Zap', Icon: Zap },
  { name: 'Wind', Icon: Wind },
  { name: 'Droplets', Icon: Droplets },
  { name: 'Shield', Icon: Shield },
  { name: 'Sword', Icon: Sword },
  { name: 'Moon', Icon: Moon },
  { name: 'Sun', Icon: Sun },
  { name: 'Sparkles', Icon: Sparkles },
  { name: 'HeartCrack', Icon: HeartCrack },
  { name: 'Eye', Icon: Eye },
  { name: 'EyeOff', Icon: EyeOff },
  { name: 'Footprints', Icon: Footprints },
  { name: 'Swords', Icon: Swords },
  { name: 'Dices', Icon: Dices },
  { name: 'Leaf', Icon: Leaf },
  { name: 'Stone', Icon: Stone },
  { name: 'Hourglass', Icon: Hourglass },
  { name: 'Target', Icon: Target },
  { name: 'LensConcave', Icon: LensConcave },
  { name: 'CircleStar', Icon: CircleStar },
  { name: 'AudioLines', Icon: AudioLines },
  { name: 'Cog', Icon: Cog },
  { name: 'TreePine', Icon: TreePine },
];

export function getStatusIcon(name?: string | null): LucideIcon | null {
  return STATUS_ICONS.find((i) => i.name === name)?.Icon ?? null;
}
